// Generated by Tools/Assets/ExportWatchMoodFrames.swift from the app's Lottie files.
enum WatchMoodAnimationFrames {
    static func count(for mood: Mood) -> Int {
        switch mood {
        case .angry: 45
        case .sad: 33
        case .mourn: 55
        case .wink: 15
        case .laughing: 30
        }
    }

    static func duration(for mood: Mood) -> Double {
        switch mood {
        case .angry: 3.0
        case .sad: 2.16
        case .mourn: 3.65
        case .wink: 1.0
        case .laughing: 1.966666748046875
        }
    }
}
